# Generated by Django 4.1.7 on 2023-03-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('investor_password', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
