# Generated by Django 4.1.7 on 2023-03-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
