# Generated by Django 4.1.7 on 2023-03-27 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tradingaccount_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingaccount',
            name='data',
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='investor_password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='login',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='platform',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='server',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='TradingAccountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('equity', models.FloatField()),
                ('balance', models.FloatField()),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tradingaccount')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
